### ISSUE TITLE
弹幕不显示

### ISSUE THREAD

**Issue by SkyShiYan** [hust201010701/XDanmuku#10]
使用过程中发现2个问题，
1：在播放大布局弹幕时的过程中，会有几率第一张图片不显示
2：在播放过程中发现当再添加新的弹幕时，之前显示又出来了

**Comment by hust201010701** [comment]
第一个问题的复现路径能否详细描述下。或者您修改哪里的代码了，贴出代码来也可以。

**Comment by SkyShiYan** [comment]
我没有修改代码

**Comment by SkyShiYan** [comment]
我发现是xml的问题

**Comment by SkyShiYan** [comment]
我先把有问题的xml贴出来：
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="wrap_content"
    android:layout_height="373dp">

    <ImageView
        android:id="@+id/iv_barrage_background"
        android:layout_width="wrap_content"
        android:layout_height="270dp"
        android:layout_alignParentStart="true"
        android:layout_alignRight="@+id/tv_barrage_msg"
        android:layout_centerVertical="true"
        android:contentDescription="@string/app_name"/>

    <ImageView
        android:id="@+id/iv_barrage_head_img"
        android:layout_width="432dp"
        android:layout_height="373dp"
        android:layout_marginEnd="20dp"
        android:contentDescription="@string/app_name"/>

    <TextView
        android:id="@+id/tv_barrage_msg"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerVertical="true"
        android:layout_toRightOf="@+id/iv_barrage_head_img"
        android:gravity="center_vertical"
        android:maxLines="1"
        android:paddingEnd="50dp"
        tools:text="asdasdasd"/>
</RelativeLayout>

**Comment by hust201010701** [comment]
能贴出来是哪里的问题么

**Comment by SkyShiYan** [comment]
我修改之后的xml：
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="wrap_content"
    android:layout_height="100dp">

    <LinearLayout
        android:id="@+id/ll_head"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:gravity="center_vertical"
        android:orientation="horizontal">

        <ImageView
            android:id="@+id/iv_barrage_head_img"
            android:layout_width="100dp"
            android:layout_height="100dp"
            android:layout_marginEnd="20dp"
            android:contentDescription="@string/app_name"/>

        <TextView
            android:id="@+id/tv_barrage_msg"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginEnd="50dp"
            android:gravity="center_vertical"
            android:maxLines="1"
            tools:text="asdasdasd"/>
    </LinearLayout>

    <ImageView
        android:id="@+id/iv_barrage_background"
        android:layout_width="wrap_content"
        android:layout_height="80dp"
        android:layout_alignParentStart="true"
        android:layout_alignRight="@+id/ll_head"
        android:layout_centerVertical="true"
        android:contentDescription="@string/app_name"/>
</RelativeLayout>

**Comment by SkyShiYan** [comment]
修改之后的xml：
<LinearLayout
        android:id="@+id/ll_head"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:gravity="center_vertical"
        android:orientation="horizontal">

        <ImageView
            android:id="@+id/iv_barrage_head_img"
            android:layout_width="100dp"
            android:layout_height="100dp"
            android:layout_marginEnd="20dp"
            android:contentDescription="@string/app_name"/>

        <TextView
            android:id="@+id/tv_barrage_msg"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginEnd="50dp"
            android:gravity="center_vertical"
            android:maxLines="1"
            tools:text="asdasdasd"/>
    </LinearLayout>

    <ImageView
        android:id="@+id/iv_barrage_background"
        android:layout_width="wrap_content"
        android:layout_height="80dp"
        android:layout_alignParentStart="true"
        android:layout_alignRight="@+id/ll_head"
        android:layout_centerVertical="true"
        android:contentDescription="@string/app_name"/>

**Comment by hust201010701** [comment]
这段代码不是我的项目中的吧，是不是你自己布局的问题。

**Comment by SkyShiYan** [comment]
对的，好像又不行了。我再试试

**Comment by SkyShiYan** [comment]
OK的，都可以显示了。是我的布局的问题

**Comment by SkyShiYan** [comment]
我刚刚使用了线程循环调用显示弹幕，发现刚开始有显示，但是之后又没有显示了。在没有显示的时候加入另一个弹幕时，之前不显示的弹幕又显示出来了。

**Comment by SkyShiYan** [comment]
我刚刚使用了每1秒加入一个1dp的view，暂时没有发现有不显示的view了。
