### ISSUE TITLE
能否设置一条一条的显示？？？

### ISSUE THREAD

**Issue by lihuanming** [hust201010701/XDanmuku#17]

**Comment by lihuanming** [comment]
快速点击会叠在一起，这种情况怎么处理？

**Comment by hust201010701** [comment]
@lihuanming 这种情况为了保证弹幕的实时性，所以允许弹幕重叠，这个库是在在寻找最合适显示的空间进行显示，如果屏幕显示满了，就会出现重叠。
一般来说，如果弹幕很多，调用方需要对弹幕进行过滤，也就是说并不需要显示所有的弹幕。
