### ISSUE TITLE
关于设置danmuContainerView.setSpeed不起作用的问题

### ISSUE THREAD

**Issue by gaochunchun** [hust201010701/XDanmuku#4]
Demo中设置弹幕的滚动速度时，除了HIGH_SPEED有效以外，其他两项不起作用。
danmuContainerView.setSpeed(DanmuContainerView.HIGH_SPEED);

----无效属性：
danmuContainerView.setSpeed(DanmuContainerView.LOW_SPEED);
danmuContainerView.setSpeed(DanmuContainerView.NORMAL_SPEED);

**Comment by hust201010701** [comment]
收到，晚上回去我去查查问题，再回复你

**Comment by hust201010701** [comment]
你好，这个bug已经修复。
如果你是在你自己的工程中添加的XDanmuView的依赖，请更新 app的 build.gradle中的依赖，修改为：
`compile 'com.github.hust201010701:XDanmuku:-SNAPSHOT'`

DanmuContainerView中预设了三种弹幕移动速度：

```java
public final static int LOW_SPEED = 1;
public final static int NORMAL_SPEED = 4;
public final static int HIGH_SPEED = 8;
```

设置速度通过setSpeed方法：
```java
danmuContainerView.setSpeed(DanmuContainerView.HIGH_SPEED);
```

同时你可以传递具体的int型速度(建议速度值在1-8之间，数值越大速度越快)：
```java
danmuContainerView.setSpeed(5);
```
